[build]
  # Configuração simplificada para debug
  base = "."
  command = "npm run build"
  publish = "build/dist"

[build.environment]
  # Variáveis de ambiente para o Eleventy
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Configuração simplificada - sem redirects complexos
