[build]
  # Diretório onde está o código fonte
  base = "."
  
  # Comando para fazer o build (instala dependências e executa build)
  command = "npm install && npm run build"
  
  # Diretório onde está o código gerado
  publish = "build/dist"
  
  # Diretório onde está o código fonte (relativo ao base)
  functions = "netlify/functions"

[build.environment]
  # Variáveis de ambiente para o Eleventy
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Configurações de redirecionamento para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de headers para cache e performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurações de compressão
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
